# Generated by Django 3.2.8 on 2021-10-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=64, verbose_name='playID')),
                ('title', models.CharField(max_length=126, verbose_name='Title')),
                ('isShared', models.CharField(max_length=40, verbose_name='Share')),
                ('hastag', models.JSONField(max_length=300, verbose_name='Hashtag')),
                ('views', models.CharField(max_length=10, verbose_name='Views')),
                ('faves', models.CharField(max_length=10, verbose_name='Likes')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
