# Generated by Django 3.2.7 on 2021-09-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField(choices=[('PT', 'Practice'), ('RD', 'Random')], max_length=4)),
                ('upload', models.TextField(choices=[('UP', 'Upload'), ('RT', 'RealTime')], max_length=4)),
                ('upload_file_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('release_date', models.TextField()),
                ('file_path', models.TextField()),
                ('sound_length', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('play_file_path', models.TextField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.option')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.option')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.song')),
            ],
        ),
    ]
