# Generated by Django 3.2.7 on 2021-09-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20210909_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='songs',
            field=models.TextField(blank=True),
        ),
    ]
