# Generated by Django 3.2.8 on 2021-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=2, max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
