# Generated by Django 3.2.7 on 2021-09-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_alter_option_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='play_file_path',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='play',
            name='option',
        ),
        migrations.RemoveField(
            model_name='play',
            name='time',
        ),
        migrations.AddField(
            model_name='play',
            name='video',
            field=models.FileField(blank=True, upload_to='play_videos'),
        ),
        migrations.AlterField(
            model_name='option',
            name='songs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='video',
            field=models.FileField(blank=True, upload_to='user_videos'),
        ),
    ]
