# Generated by Django 3.2.7 on 2021-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_auto_20210912_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='user_videos'),
        ),
    ]
