# Generated by Django 3.2.7 on 2021-10-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_play_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsong',
            name='option_id',
        ),
        migrations.RemoveField(
            model_name='optionsong',
            name='songs',
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionSong',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
